package gg.modl.backend.player.service;

import gg.modl.backend.player.data.punishment.Punishment;
import gg.modl.backend.player.data.punishment.PunishmentNote;
import gg.modl.backend.settings.data.PunishmentType;
import gg.modl.proto.modl.v1.SimplePunishment;
import gg.modl.proto.modl.v1.SyncPunishmentModification;
import gg.modl.proto.modl.v1.SyncPunishmentWithModifications;
import java.util.Date;
import java.util.Map;

final class SimplePunishmentProtoMapper {

    private SimplePunishmentProtoMapper() {
    }

    static SimplePunishment toSimplePunishment(
        Punishment punishment,
        Map<Integer, PunishmentType> typesByOrdinal,
        PlayerStatusCalculator statusCalculator,
        Map<String, String> resolvedIssuers
    ) {
        Map<String, Object> data = punishment.getData();
        Date expires = statusCalculator.getEffectiveExpiry(punishment);
        PunishmentType punishmentType = typesByOrdinal.get(punishment.getTypeOrdinal());

        String typeName = punishmentType != null ? punishmentType.getName() : "Unknown";
        String playerDescription = punishmentType != null ? punishmentType.getPlayerDescription() : null;

        String effectiveCategory = statusCalculator.getEffectiveCategory(punishmentType, data);
        String category = effectiveCategory != null ? effectiveCategory : "OTHER";

        String reason = extractReason(punishment);
        String description = reason != null ? reason : "No reason specified";
        String issuerName = PunishmentMapper.resolveIssuer(
            punishment.getIssuerId(),
            punishment.getIssuerName(),
            resolvedIssuers
        );

        SimplePunishment.Builder builder = SimplePunishment.newBuilder()
            .setId(punishment.getId())
            .setType(typeName)
            .setCategory(category)
            .setOrdinal(punishment.getTypeOrdinal())
            .setStarted(punishment.getStarted() != null)
            .setDescription(description)
            .setIssuerName(issuerName)
            .setIssuedAt(punishment.getIssued().getTime());

        if (expires != null) {
            builder.setExpiration(expires.getTime());
        }
        if (playerDescription != null) {
            builder.setPlayerDescription(playerDescription);
        }
        return builder.build();
    }

    static SyncPunishmentWithModifications toPunishmentWithModifications(Punishment punishment) {
        SyncPunishmentWithModifications.Builder builder = SyncPunishmentWithModifications.newBuilder()
            .setId(punishment.getId());

        punishment.getModifications().forEach(modification -> {
            SyncPunishmentModification.Builder modBuilder = SyncPunishmentModification.newBuilder()
                .setType(modification.type() != null ? modification.type() : "");
            if (modification.date() != null) {
                modBuilder.setTimestamp(modification.date().getTime());
            }
            if (modification.effectiveDuration() != null) {
                modBuilder.setEffectiveDuration(modification.effectiveDuration());
            }
            builder.addModifications(modBuilder.build());
        });
        return builder.build();
    }

    private static String extractReason(Punishment punishment) {
        if (punishment.getTypeOrdinal() > 5 || punishment.getNotes() == null || punishment.getNotes().isEmpty()) {
            return null;
        }
        for (PunishmentNote note : punishment.getNotes()) {
            String noteText = note.text();
            if (noteText != null && !PunishmentMapper.isAutoGeneratedNote(noteText)) {
                return noteText;
            }
        }
        return null;
    }
}
